version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      DATABASE_URL: "mongodb://mongo:27017/support-ticket"
      PORT: 8000
      DATABASE: "support-ticket"
      JWT_KEY: "rffdfw423ef423r3"
      ADMIN_EMAIL: "admin@test.info"
      ADMIN_PASSWORD: "adminPassword"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
